// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Listmodule: typeof import('./src/components/common/listmodule.vue')['default']
    MyFooter: typeof import('./src/components/my-footer/MyFooter.vue')['default']
    MyMain: typeof import('./src/components/my-main/MyMain.vue')['default']
    MyNav: typeof import('./src/components/my-nav/MyNav.vue')['default']
    PlayMusic: typeof import('./src/components/my-play/PlayMusic.vue')['default']
    RankList: typeof import('./src/components/my-rank/RankList.vue')['default']
    RecommendMv: typeof import('./src/components/my-discover/RecommendMv.vue')['default']
    RecommendNew: typeof import('./src/components/my-discover/RecommendNew.vue')['default']
    RecommendScroll: typeof import('./src/components/my-discover/RecommendScroll.vue')['default']
    RecommendSheet: typeof import('./src/components/my-discover/RecommendSheet.vue')['default']
    RecommendSinger: typeof import('./src/components/my-discover/RecommendSinger.vue')['default']
    Sheet: typeof import('./src/components/common/sheet.vue')['default']
    SvgIcon: typeof import('./src/components/common/svgIcon/SvgIcon.vue')['default']
  }
}

export { }
