// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoutiqueSongSheetCard: typeof import('./src/components/song-sheet/BoutiqueSongSheetCard.vue')['default']
    Carousel: typeof import('./src/components/discover-music/Carousel.vue')['default']
    ContentBox: typeof import('./src/components/common/ContentBox.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Empty: typeof import('./src/components/common/Empty.vue')['default']
    Footer: typeof import('./src/components/home-page/Footer.vue')['default']
    ListModule: typeof import('./src/components/common/ListModule.vue')['default']
    Loading: typeof import('./src/components/common/loading/Loading.vue')['default']
    LoadingIcon: typeof import('./src/components/common/loading/LoadingIcon.vue')['default']
    LoadScroll: typeof import('./src/components/common/LoadScroll.vue')['default']
    Lyric: typeof import('./src/components/lyric/Lyric.vue')['default']
    Main: typeof import('./src/components/home-page/Main.vue')['default']
    MvList: typeof import('./src/components/mv/MvList.vue')['default']
    MvSheet: typeof import('./src/components/mv/MvSheet.vue')['default']
    Nav: typeof import('./src/components/home-page/Nav.vue')['default']
    NewSongSheet: typeof import('./src/components/new-disc/NewSongSheet.vue')['default']
    ProgressBar: typeof import('./src/components/progress-bar/ProgressBar.vue')['default']
    RankShow: typeof import('./src/components/rank/RankShow.vue')['default']
    Scroll: typeof import('./src/components/lyric/Scroll.vue')['default']
    SearchMusic: typeof import('./src/components/search/SearchMusic.vue')['default']
    SingerAlbum: typeof import('./src/components/singer/SingerAlbum.vue')['default']
    SingerMsg: typeof import('./src/components/singer/SingerMsg.vue')['default']
    SingerSheet: typeof import('./src/components/singer/SingerSheet.vue')['default']
    SongList: typeof import('./src/components/song-sheet/SongList.vue')['default']
    SongSheetCard: typeof import('./src/components/song-sheet/SongSheetCard.vue')['default']
    SvgIcon: typeof import('./src/components/common/svgIcon/SvgIcon.vue')['default']
    TalkList: typeof import('./src/components/common/TalkList.vue')['default']
  }
}

export { }
