// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    MyFooter: typeof import('./src/components/my-footer/MyFooter.vue')['default']
    MyMain: typeof import('./src/components/my-main/MyMain.vue')['default']
    MyNav: typeof import('./src/components/my-nav/MyNav.vue')['default']
    PlayMusic: typeof import('./src/components/my-play/PlayMusic.vue')['default']
    RankList: typeof import('./src/components/my-rank/RankList.vue')['default']
    RecommedNew: typeof import('./src/components/my-discover/RecommedNew.vue')['default']
    RecommendSheet: typeof import('./src/components/my-discover/RecommendSheet.vue')['default']
    RecommendSinger: typeof import('./src/components/my-discover/RecommendSinger.vue')['default']
  }
}

export { }
